#!/bin/bash

rm -rf "${1}.pdf"
arara "${@}"
set -f
echo -n "Deleting temporary files... "
EXCEPTIONS=$(echo '*.tex *.sty *.bib *.svg *.png *.md LICENCE *.pdf build .gitignore .git');
PARAMETERS=$(echo $EXCEPTIONS | sed -e "s|[^ ][^ ]*|-not -name '&'|g")
set +f
DELETEABLE=$(eval "find . \( ! -regex '.*/\..*' \) -type f ${PARAMETERS} | xargs rm");
sleep 2
echo "SUCCESS"
echo ""
echo "===================================="
echo ""
echo "Output may be found in ${1}.pdf"
echo ""
echo "BUILD COMPLETE"